"""Rule catalogue (one rule per feature). Explainer functions are added in Phase 3."""

RULES = [
    {"feature": "url_length", "triggers_when": lambda v: v > 75,
     "label": "Unusually long URL",
     "why": "Very long web addresses can be used to push the real destination out of sight in the address bar."},
    {"feature": "hostname_length", "triggers_when": lambda v: v > 30,
     "label": "Unusually long domain name",
     "why": "Long domain names are sometimes used to imitate a trusted brand or to bury the part that identifies the real site."},
    {"feature": "path_length", "triggers_when": lambda v: v > 40,
     "label": "Unusually long path after the domain",
     "why": "A long trail of folders and file names after the domain can be used to make an address look official or to hide what matters."},
    {"feature": "num_dots", "triggers_when": lambda v: v > 3,
     "label": "Many dots in the address",
     "why": "A lot of dots often means several sections are stacked before the real domain, which can make a fake address look genuine."},
    {"feature": "num_hyphens", "triggers_when": lambda v: v >= 3,
     "label": "Several hyphens in the address",
     "why": "Hyphens are often used to string together brand-like words, such as invented 'secure' or 'login' names."},
    {"feature": "num_digits", "triggers_when": lambda v: v > 10,
     "label": "Many digits in the address",
     "why": "Long runs of numbers are uncommon in genuine website names and are often seen in automatically generated addresses."},
    {"feature": "num_special_chars", "triggers_when": lambda v: v >= 3,
     "label": "Unusual symbols in the address",
     "why": "Symbols such as ?, =, & or % are common in tracking and redirect links, which are sometimes used to hide the final destination."},
    {"feature": "num_subdomains", "triggers_when": lambda v: v >= 3,
     "label": "Many sub-domains",
     "why": "Extra sections before the main domain can be used to make an address appear to belong to a trusted company."},
    {"feature": "has_https", "triggers_when": lambda v: v == 0,
     "label": "Connection is not encrypted (no HTTPS)",
     "why": "Genuine sign-in pages almost always use an encrypted connection, so its absence is unusual for a page asking for personal details."},
    {"feature": "has_ip_address", "triggers_when": lambda v: v == 1,
     "label": "Address uses a raw IP instead of a domain name",
     "why": "Genuine services almost always use a domain name. A bare IP address is unusual for a login page."},
    {"feature": "has_at_symbol", "triggers_when": lambda v: v == 1,
     "label": "Address contains an @ symbol",
     "why": "Browsers ignore the text before an @ symbol in an address, which can be used to disguise the real destination."},
    {"feature": "suspicious_keyword_count", "triggers_when": lambda v: v >= 2,
     "label": "Sensitive words in the address",
     "why": "Words like 'login', 'verify' or 'account' are often associated with pages trying to look like real sign-in pages."},
]

TOTAL_RULES = len(RULES)
